version: '3'
services:  
  rabbitmq:
    image: "rabbitmq:management"  # Using the management image gives you access to a web-based UI
    ports:
      - "15672:15672"  # Management UI
      - "5672:5672"    # Default RabbitMQ port
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  # ffmpeg-worker:
  #   build:
  #     context: .
  #     Dockerfile: Dockerfile.worker  # Dockerfile for your FFmpeg worker setup
  #   depends_on:
  #     - rabbitmq  # Ensure RabbitMQ starts first
